Kifiya-Agentic-HR/Agentic-HR-System

DB schema

Update DB schema

---

docker-compose.yaml
services/job_service/backend/app/utils/cloud_storage.py

[ENH] Fix ACL Issue with buckets

---

services/job_service/frontend/src/app/page.tsx
services/job_service/frontend/src/components/jobs-grid.tsx
services/job_service/frontend/src/components/site-footer.tsx

💼Careers Page
- [] Conform to the new schema

Add careers page

---

services/job_service/frontend/src/actions/get-jobs.ts
services/job_service/frontend/src/app/globals.css
services/job_service/frontend/src/app/page.tsx
services/job_service/frontend/src/components/jobs-grid.tsx

📝 Job Filtering Feature for Careers Page

Added job filtering per role, skills and type on  careers page

---

docker-compose.yaml
services/interview_ai/backend/requirements.txt
services/interview_ai/backend/src/api/core/config.py
services/interview_ai/backend/src/api/core/weaviate.py
services/interview_ai/backend/src/api/routes/ingestion/__init__.py
services/interview_ai/backend/src/api/routes/ingestion/ingestion.py
services/interview_ai/backend/src/api/routes/ingestion/retrieval.py
services/interview_ai/backend/src/api/services/file_processor.py

[ENH] Added RAG Server

---

services/interview_ai/backend/src/api/core/config.py
services/interview_ai/backend/src/api/main.py
services/interview_ai/frontend/Dockerfile

Fix minor errors on interview module

---

.env.example
docker-compose.yaml
services/cms/frontend/package-lock.json
services/cms/frontend/package.json
services/cms/frontend/src/components/Chatbot.tsx

[ENH]HR chatbot feature

---

.env.example
services/job_service/backend/app/routes/applications.py
services/notification/app/schemas.py
services/notification/app/services/template_renderer.py
services/notification/app/templates/application_passed.html
services/notification/app/templates/application_rejected.html

[ENH] Add Cuztomized Email

---

services/cms/backend/src/jobs/jobs.controller.ts
services/cms/backend/src/jobs/jobs.service.ts

[ENH] Fixed Integration

---

services/cms/frontend/src/app/hr/job-post/page.tsx
services/cms/frontend/src/components/JobPostingChatbot.tsx

[FEAT]-Job Posting AI Assistant

---

services/cms/backend/src/applications/applications.controller.ts
services/cms/backend/src/applications/applications.module.ts
services/cms/backend/src/users/users.controller.ts
services/cms/frontend/src/app/applications/[jobId]/page.tsx
services/cms/frontend/src/components/jobs/types.ts
services/cms/frontend/src/lib/api.ts
services/job_service/backend/app/database/models/application_model.py
services/job_service/backend/app/routes/applications.py
services/job_service/backend/app/schemas/shortlist_schema.py

[ADD] Feature persistent notes

---

.github/workflow/deploy.yml

[ENH] Added Autoamted CI/CD Setup

---

services/interview_ai/backend/src/api/routes/interview/__init__.py

interview link expires now

---

services/cms/frontend/package-lock.json
services/cms/frontend/package.json
services/cms/frontend/src/app/admin/page.tsx
services/cms/frontend/src/app/hm/page.tsx
services/cms/frontend/src/app/hr/page.tsx
services/cms/frontend/src/components/ProfileDropdown.tsx

Fix job list

---

services/cms/frontend/src/app/hr/job-post/page.tsx
services/cms/frontend/src/components/JobPostingChatbot.tsx

Reverts Kifiya-Agentic-HR/Agentic-HR-System#158

Revert "Job posting AI feature with Autofill"

---

services/cms/frontend/src/app/hr/job-post/page.tsx

job posting ai features

---

services/cms/frontend/src/app/hr/job-post/page.tsx
services/cms/frontend/src/components/JobPostingChatbot.tsx

jobposting ai feature with autofill

---

services/cms/frontend/src/app/hr/job-post/page.tsx
services/cms/frontend/src/lib/api.ts

job file upload integration

---

services/job_service/frontend/src/components/apply-form.tsx

Verify Email Notice

---

services/interview_ai/backend/src/api/routes/interview/scheduling.py

interview notification link added
